---

- name: Install SAMBA
  become: yes
  become_user: root
  apt: name="{{ item }}"
  with_items:
    - samba
    - smbclient

- name: Install base SAMBA configuration
  become: yes
  become_user: root
  template:
    src: "etc/samba/smb.conf.j2"
    dest: "/etc/samba/smb.conf"
  notify: "Restart SAMBA"
